### ISSUE TITLE
Ajustar Open Graph Meta Tags

### ISSUE THREAD

**Issue by juanpablo-is** [Afordin/hackafor#16]
Ajustar MetaTags OpenGraphs, actualmente se tiene 3 tags (image, title y description)

- image, no está cargando debido al path, remover `/public`
- description, aumentar la cantidad de caracteres alrededor de 100 (recomendación de Linkedin)

**Comment by JoeMancera** [comment]
Tomaré este issue 🏃‍♂️💨

**Comment by JoeMancera** [comment]
Por aquí la PR para resolver el Issue con un par de mejoras
- #20
